use_frameworks!

target 'RxMVC_Example' do
  platform :ios, '9.0'
  pod 'RxMVC', :path => '../'
  pod 'Reachability', '~> 3.0'
  pod 'RxAlamofire', :git => 'https://github.com/Hardtack/RxAlamofire.git'
  pod 'Alamofire', '~> 4.0'
  pod 'Toaster', '~> 2.0'

  target 'RxMVC_Tests' do
    inherit! :search_paths
    platform :ios, '9.0'

    pod 'RxBlocking', '~> 3.0.0-beta.1'
    pod 'RxTests',    '~> 3.0.0-beta.1'
  end
end
