use_frameworks!

target 'RxMVC_Example' do
  pod 'RxMVC', :path => '../'
  pod 'Reachability', '~> 3.0'
  pod 'RxAlamofire', '~> 2.0'
  pod 'JLToast', '~> 1.4'

  target 'RxMVC_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'RxBlocking', '~> 2.0'
    pod 'RxTests',    '~> 2.0'
    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
