osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
rvm:
  - 2.3.1
before_install:
  - sudo gem install bundler
  - bundle install
  - pod repo update
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/RxMVC.xcworkspace -scheme RxMVC-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
