osx_image: xcode7.3
rvm:
  - 2.3.1
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
install:
- bundle install
- pod repo remove master
- pod setup
- bundle exec pod install --project-directory=Example
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/RxMVC.xcworkspace -scheme RxMVC-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

