osx_image: xcode7.3
rvm:
  - 2.3.1
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
- bundle install
- pod repo remove master
- pod setup
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- bundle exec pod install --project-directory=Example
script:
- >
  set -o pipefail &&
  xcodebuild test
  -workspace Example/RxMVC.xcworkspace
  -scheme RxMVC-Example
  -sdk iphonesimulator9.3
  -jobs `sysctl hw.ncpu | awk '{print 2*$2}'`
  ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

