osx_image: xcode7.3
language: objective-c
rvm:
  - 2.3.1
cache: cocoapods
podfile: Example/Podfile
before_install:
- bundle install
- pod repo update
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/RxMVC.xcworkspace -scheme RxMVC-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

